### ISSUE TITLE
백앤드 오류

### ISSUE THREAD

**Issue by sinokadev** [abiriadev/sinedict#2]
![image](https://github.com/abiriadev/sinedict/assets/94734506/7e0a8697-3865-43c7-ab7c-3c977012570b)

**Comment by sinokadev** [comment]
이런식으로 사이트가 안뜹니다

**Comment by abiriadev** [comment]
@newkincode 오랜 미사용으로 백엔드 세션이 자동 정지되어서 발생하는 오류입니다.

현재 임시로 다시 작동시켜 두었습니다. 혹시 본 서비스를 계속 사용하길 원하시나요? 그렇다면 항상 켜둘 수 있도록 설정하겠습니다.

**Comment by sinokadev** [comment]
ㅇㅎ 감사합니다 그러면 필요할떄 여기다 말할께요
